# Generated by Django 3.1.6 on 2021-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pool', models.IntegerField()),
                ('id_channel', models.IntegerField()),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
